export const PAPER_PLANE_ICON = '/paper-plane.png';
export const FAVICON = '/favicon.ico';
export const AVATAR_MAN =
  'https://ik.imagekit.io/Victorliradev/bossa-nova-solutions/man_H13Xy31hu.png?updatedAt=1734122241755';
export const STAR_ICON =
  'https://ik.imagekit.io/Victorliradev/bossa-nova-solutions/star_KIFvUb4oZ.png?updatedAt=1734122679885';
export const SEARCH_ICON =
  'https://ik.imagekit.io/Victorliradev/bossa-nova-solutions/search-gray_HRrq0YV59.webp?updatedAt=1734181264915';
export const CLOSE_ICON =
  'https://ik.imagekit.io/Victorliradev/bossa-nova-solutions/close_43iIxrIYi.png?updatedAt=1734184751036';
